x-env-vars: &env-vars
  env_file:
    - .env

services:
  postgres-db:
    image: "postgres:16-bookworm"
    restart: always
    ports:
      - "5432:5432"
    <<: *env-vars

  memcache:
    image: memcached:bookworm
    restart: always
    ports:
      - "11211:11211"
