# Generated by Django 5.0.6 on 2024-06-05 13:42

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="courses_joined",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
