# Generated by Django 5.0.6 on 2024-06-17 10:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "name",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
